--dropRiverTables.sql
--Name: Marissa Gonçalves
--Due Date: November 16, 2018


--Part 3: Populate the Tables and Show Contents

--b)

DROP TABLE CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE ITEM CASCADE CONSTRAINTS;
DROP TABLE PURCHASE CASCADE CONSTRAINTS;
DROP TABLE PURCHASE_ITEM CASCADE CONSTRAINTS;

