--showRiverTables.sql
--Name: Marissa Gonçalves
--Due Date: November 16, 2018


--Part 3: Populate the Tables and Show Contents

--c)

DESCRIBE CUSTOMER;
DESCRIBE ITEM;
DESCRIBE PURCHASE;
DESCRIBE PURCHASE_ITEM;




SELECT * FROM CUSTOMER;


SELECT * FROM ITEM;


SELECT * FROM PURCHASE;


SELECT * fROM PURCHASE_ITEM;





SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'CUSTOMER';


SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'ITEM';


SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'PURCHASE';


SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'PURCHASE_ITEM';